- id: '1704194273528'
  alias: Create backup
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1704200208287'
  alias: Sunset light
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition: []
  action:
  - type: turn_on
    device_id: f4242b9122aad3a276e0e134b9f2a77d
    entity_id: cf7bcbd7414e37970a11ade0f3633d67
    domain: light
  mode: single
- id: '1717655923777'
  alias: Electricity not detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.electricity_detector_relay_voltage
    from:
    to: unavailable
  condition: []
  action:
  - type: turn_off
    device_id: eb6e5b4a4664fda5366635a02f6a179f
    entity_id: fa44e5ac4a0df6c54e27397459eb45ee
    domain: switch
  - type: turn_off
    device_id: cde3cbfdda2198258f8fa8a479cd3358
    entity_id: f8c3eb16e1e78bc7b12b1619d8838365
    domain: switch
  - service: notify.notify
    metadata: {}
    data:
      message: "Electricity not detected \U0001F50C"
  mode: single
- id: '1717656035531'
  alias: Electricity detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.electricity_detector_relay_voltage
    from: unavailable
    to:
  condition: []
  action:
  - type: turn_on
    device_id: eb6e5b4a4664fda5366635a02f6a179f
    entity_id: fa44e5ac4a0df6c54e27397459eb45ee
    domain: switch
  - type: turn_on
    device_id: cde3cbfdda2198258f8fa8a479cd3358
    entity_id: f8c3eb16e1e78bc7b12b1619d8838365
    domain: switch
  - service: notify.notify
    metadata: {}
    data:
      message: Electricity detected ⚡
  mode: single
- id: '1719304706918'
  alias: Anton's Desktop Led Button Single click
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: c97304da42e5614a8f03c760bfd7e3bc
    type: action
    subtype: single
  condition: []
  action:
  - type: toggle
    device_id: ec88a148fbe20ff6e69eb7c013f96172
    entity_id: 9ccec3dd1cc9a1322a4649ca7b57f53d
    domain: light
  mode: single
- id: '1720421849927'
  alias: Internet speed test
  description: ''
  trigger:
  - platform: time_pattern
    hours: /2
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
      - sensor.speedtest_download
      - automation.internet_speed_test
      - sensor.speedtest_ping
  mode: single
- id: '1723288853366'
  alias: Microgreen display
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: 0
  condition: []
  action:
  - service: script.microgreen_display
    metadata: {}
    data: {}
  mode: single
- id: '1723294629565'
  alias: Spotify display
  description: ''
  trigger: []
  condition: []
  action:
  - service: spotifyplus.get_player_now_playing
    data:
      entity_id: media_player.spotifyplus_anton_isaiev
      additional_types: track,episode
    response_variable: track
  - service: persistent_notification.create
    data:
      message: '{{ track.result.item.name }}'
    enabled: true
  - service: open_epaper_link.drawcustom
    target:
      entity_id:
      - open_epaper_link.0284a29d3b1b0284
    data:
      background: white
      rotate: 0
      payload:
      - type: dlimg
        url: '{{ track.result.item.album.images[0].url }}'
        x: 0
        y: 0
        xsize: 148
        ysize: 128
        rotate: 0
      - type: text
        value: '{{ track.result.item.name }}'
        size: 15
        max_width: 146
        x: 150
        y: 40
      - type: text
        value: '{{ track.result.item.album.artists[0].name }}'
        color: red
        size: 12
        max_width: 146
        x: 150
  mode: single
- id: '1723367150124'
  alias: Weather station display
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /30
  condition: []
  action:
  - service: open_epaper_link.drawcustom
    target:
      entity_id:
      - open_epaper_link.0284a29d3b1b0284
    data:
      background: white
      rotate: 0
      payload:
      - type: text
        value: Kyiv
        x: 5
        y: 5
        font: rbm.ttf
        size: 23
      - type: icon
        value: thermometer
        x: 0
        y: 30
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.esp32_weather_station_temperature'') | round(1)}}
          °C'
        x: 25
        y: 33
        size: 17
        font: rbm.ttf
      - type: icon
        value: water-percent
        x: 0
        y: 60
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.esp32_weather_station_humidity'') | round(1)}} %'
        x: 25
        y: 63
        size: 17
        font: rbm.ttf
      - type: icon
        value: gauge
        x: 0
        y: 90
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.esp32_weather_station_pressure'') | round(1)}} hPa'
        x: 25
        y: 93
        size: 17
        font: rbm.ttf
      - type: icon
        value: air-filter
        x: 200
        y: 30
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.lun_misto_air_301_air_quality_index'')}}'
        x: 225
        y: 33
        size: 17
        font: rbm.ttf
      - type: icon
        value: sine-wave
        x: 200
        y: 60
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.esp32_weather_station_battery_voltage'') | round(2)}}
          V'
        x: 225
        y: 63
        size: 17
        font: rbm.ttf
      - type: icon
        value: battery
        x: 200
        y: 90
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.esp32_weather_station_battery_level'') | round(1)}}
          %'
        x: 225
        y: 95
        size: 17
        font: rbm.ttf
      - type: text
        value: '{{ as_timestamp(states(''sensor.date_time_iso'')) | timestamp_custom(''%d.%m.%Y'')
          }}'
        x: 291
        y: 10
        size: 12
        font: rbm.ttf
        anchor: rt
      - type: text
        value: 'Last updated: {{ as_timestamp(states(''sensor.date_time_iso'')) |
          timestamp_custom(''%H:%M'') }}'
        x: 291
        y: 118
        size: 10
        font: rbm.ttf
        anchor: rt
  mode: single
- id: '1723999952515'
  alias: Microgreen state changed
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: 6863e46227539236ca00f23410ae67d0
    entity_id: a95baa0ca51cc1a47a7e5d671cc57cb9
    domain: light
  - platform: device
    type: changed_states
    device_id: 6863e46227539236ca00f23410ae67d0
    entity_id: cafeb4d13222e3c10481b40835defb72
    domain: switch
  - platform: device
    type: changed_states
    device_id: 7dbd9b5e3b147c5ee6174acb7f2da69d
    entity_id: 159387738f0ad2f9c10c237d9e135942
    domain: light
  - platform: device
    type: changed_states
    device_id: 7dbd9b5e3b147c5ee6174acb7f2da69d
    entity_id: 98fbf9eeb28adfe7a94d7555d30399fe
    domain: switch
  condition: []
  action:
  - service: script.microgreen_display
    metadata: {}
    data: {}
  mode: single
- id: '1724934618093'
  alias: Ecoflow Delta Pro display
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  - platform: state
    entity_id:
    - sensor.bolek_status
    from: assume_offline
    to: assume_online
  - platform: device
    type: changed_states
    device_id: 7b97b4ab00c199201c4d4878de2283db
    entity_id: 4148925d69e8f76be84970a9e9c263fb
    domain: switch
  condition:
  - condition: state
    entity_id: sensor.bolek_status
    state: assume_online
  action:
  - service: open_epaper_link.drawcustom
    target:
      entity_id:
      - open_epaper_link.0284a3393b140284
    data:
      background: white
      rotate: 0
      payload:
      - type: text
        value: Bolek
        x: 5
        y: 5
      - type: text
        value: '{{ as_timestamp(states(''sensor.date_time_iso'')) | timestamp_custom(''%d-%m-%Y,
          %H:%M'') }}'
        x: 291
        y: 10
        size: 10
        anchor: rt
      - type: line
        x_start: 5
        x_end: 291
        y_start: 25
        y_end: 25
        width: 1
        fill: red
      - type: progress_bar
        x_start: 5
        y_start: 98
        x_end: 291
        y_end: 123
        fill: red
        outline: black
        width: 1
        progress: '{{states(''sensor.bolek_battery_level'')}}'
        direction: right
      - type: text
        value: '{{states(''sensor.bolek_battery_level'')}} %'
        x: 148
        y: 82
        size: 15
        anchor: mt
      - type: text
        value: "{% if states('sensor.bolek_total_in_power') | int > 0 %}\n  {{states('sensor.bolek_charge_remaining_time')
          | int // 60}}h {{states('sensor.bolek_charge_remaining_time') | int % 60}}m\n{%
          else %}\n  {{states('sensor.bolek_discharge_remaining_time') | int // 60}}h
          {{states('sensor.bolek_discharge_remaining_time') | int % 60}}m\n{% endif
          %}"
        x: 5
        y: 50
        size: 25
      - type: text
        value: 'In: {{states(''sensor.bolek_total_in_power'')}} W'
        x: 291
        y: 40
        anchor: rt
        size: 17
      - type: text
        value: 'Out: {{states(''sensor.bolek_total_out_power'')}} W'
        x: 291
        y: 70
        anchor: rt
        size: 17
  mode: single
- id: '1724943986455'
  alias: Ecoflow Delta Pro turned off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.bolek_status
    from: assume_online
    to: assume_offline
  condition: []
  action:
  - service: open_epaper_link.drawcustom
    target:
      entity_id:
      - open_epaper_link.0284a3393b140284
    data:
      background: white
      rotate: 0
      payload:
      - type: text
        value: Bolek
        x: 5
        y: 5
      - type: text
        value: '{{ as_timestamp(states(''sensor.date_time_iso'')) | timestamp_custom(''%d-%m-%Y,
          %H:%M'') }}'
        x: 291
        y: 10
        size: 10
        anchor: rt
      - type: line
        x_start: 5
        x_end: 291
        y_start: 25
        y_end: 25
        width: 1
        fill: red
      - type: icon
        value: power-plug-off
        x: 148
        y: 74
        size: 70
        color: black
        anchor: mm
  mode: single
