- id: '1704194273528'
  alias: Create backup
  description: ''
  triggers:
  - at: 00:00:00
    trigger: time
  conditions: []
  actions:
  - action: auto_backup.backup_full
    data:
      compressed: true
      keep_days: 5
  mode: single
- id: '1704200208287'
  alias: Sunset light
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition: []
  action:
  - type: turn_on
    device_id: f4242b9122aad3a276e0e134b9f2a77d
    entity_id: cf7bcbd7414e37970a11ade0f3633d67
    domain: light
  mode: single
- id: '1723288853366'
  alias: Microgreen display
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: 0
  condition: []
  action:
  - service: script.microgreen_display
    metadata: {}
    data: {}
  mode: single
- id: '1723294629565'
  alias: Spotify display
  description: ''
  triggers:
  - trigger: time_pattern
    minutes: /1
  - trigger: state
    entity_id:
    - media_player.spotifyplus_anton_isaiev
    from: paused
    to: playing
  - trigger: state
    entity_id:
    - media_player.spotifyplus_anton_isaiev
    from: 'off'
    to: playing
  conditions:
  - condition: state
    entity_id: media_player.spotifyplus_anton_isaiev
    state: playing
  actions:
  - data:
      entity_id: media_player.spotifyplus_anton_isaiev
      additional_types: track,episode
    response_variable: track
    action: spotifyplus.get_player_now_playing
  - target:
      entity_id:
      - open_epaper_link.0000021ed5013b1d
    data:
      background: white
      rotate: 0
      payload:
      - type: dlimg
        url: '{{ track.result.item.album.images[0].url }}'
        x: 5
        y: 5
        xsize: 120
        ysize: 120
        rotate: 0
      - type: text
        value: '{{ track.result.item.name }}'
        size: 18
        max_width: 166
        x: 213
        y: 40
        anchor: ma
      - type: text
        value: '{{ track.result.item.album.artists[0].name }}'
        color: red
        size: 14
        x: 213
        anchor: mb
        y_padding: 20
    action: open_epaper_link.drawcustom
  mode: single
- id: '1723367150124'
  alias: Weather station display
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /30
  condition: []
  action:
  - target:
      entity_id:
      - open_epaper_link.0284a29d3b1b0284
    data:
      background: white
      rotate: 0
      payload:
      - type: text
        value: Kyiv
        x: 5
        y: 5
      - type: text
        value: '{{ as_timestamp(states(''sensor.date_time_iso'')) | timestamp_custom(''%d.%m.%Y'')
          }}'
        x: 291
        y: 10
        size: 10
        anchor: rt
      - type: line
        x_start: 5
        x_end: 291
        y_start: 27
        y_end: 27
        width: 1
        fill: red
      - type: icon
        value: thermometer
        x: 0
        y: 32
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.solar_weather_station_temperature'') | round(1)}}
          °C'
        x: 25
        y: 37
        size: 15
      - type: icon
        value: water-percent
        x: 0
        y: 62
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.solar_weather_station_humidity'') | round(1)}} %'
        x: 25
        y: 67
        size: 15
      - type: icon
        value: gauge
        x: 0
        y: 92
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.solar_weather_station_pressure_2'') | round(1)}}
          hPa'
        x: 25
        y: 97
        size: 15
      - type: icon
        value: air-filter
        x: 200
        y: 32
        size: 20
        color: red
      - type: text
        value: "{% if states(\"sensor.lun_misto_air_301_air_quality_index\") != \"unavailable\"
          -%}\n  {{states(\"sensor.lun_misto_air_301_air_quality_index\")}}\n{%- else
          -%}\n  {{states(\"sensor.lun_misto_air_37_air_quality_index\")}}\n{%- endif
          %}"
        x: 225
        y: 37
        size: 15
      - type: icon
        value: sine-wave
        x: 200
        y: 62
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.solar_weather_station_battery_voltage_2'') | round(2)}}
          V'
        x: 225
        y: 67
        size: 15
      - type: icon
        value: battery
        x: 200
        y: 92
        size: 20
        color: red
      - type: text
        value: '{{states(''sensor.solar_weather_station_battery_level_2'') | round(1)}}
          %'
        x: 225
        y: 97
        size: 15
      - type: text
        value: 'Last updated: {{ as_timestamp(states(''sensor.date_time_iso'')) |
          timestamp_custom(''%H:%M'') }}'
        x: 291
        y: 118
        size: 10
        anchor: rt
    action: open_epaper_link.drawcustom
  mode: single
- id: '1723999952515'
  alias: Microgreen state changed
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: 6863e46227539236ca00f23410ae67d0
    entity_id: a95baa0ca51cc1a47a7e5d671cc57cb9
    domain: light
  - platform: device
    type: changed_states
    device_id: 6863e46227539236ca00f23410ae67d0
    entity_id: cafeb4d13222e3c10481b40835defb72
    domain: switch
  - platform: device
    type: changed_states
    device_id: 7dbd9b5e3b147c5ee6174acb7f2da69d
    entity_id: 159387738f0ad2f9c10c237d9e135942
    domain: light
  - platform: device
    type: changed_states
    device_id: 7dbd9b5e3b147c5ee6174acb7f2da69d
    entity_id: 98fbf9eeb28adfe7a94d7555d30399fe
    domain: switch
  condition: []
  action:
  - service: script.microgreen_display
    metadata: {}
    data: {}
  mode: single
- id: '1724934618093'
  alias: Ecoflow Delta Pro display
  description: ''
  triggers:
  - minutes: /10
    trigger: time_pattern
  - entity_id:
    - sensor.bolek_status
    from: assume_offline
    to: assume_online
    trigger: state
  - entity_id:
    - switch.bolek_ac_enabled
    from: 'on'
    to: 'off'
    trigger: state
  - entity_id:
    - switch.bolek_ac_enabled
    from: 'off'
    to: 'on'
    trigger: state
  conditions:
  - condition: state
    entity_id: sensor.bolek_status
    state: online
  actions:
  - target:
      entity_id:
      - open_epaper_link.0284a3393b140284
    data:
      background: white
      rotate: 0
      payload:
      - type: text
        value: Bolek
        x: 5
        y: 5
      - type: text
        value: '{{ as_timestamp(states(''sensor.date_time_iso'')) | timestamp_custom(''%d-%m-%Y,
          %H:%M'') }}'
        x: 291
        y: 10
        size: 10
        anchor: rt
      - type: line
        x_start: 5
        x_end: 291
        y_start: 25
        y_end: 25
        width: 1
        fill: red
      - type: progress_bar
        x_start: 5
        y_start: 98
        x_end: 291
        y_end: 123
        fill: red
        outline: black
        width: 1
        progress: '{{states(''sensor.bolek_battery_level'')}}'
        direction: right
      - type: text
        value: '{{states(''sensor.bolek_battery_level'')}} %'
        x: 148
        y: 82
        size: 15
        anchor: mt
      - type: text
        value: "{% if states('sensor.bolek_total_in_power') | int > 0 %}\n  {{states('sensor.bolek_charge_remaining_time')
          | int // 60}}h {{states('sensor.bolek_charge_remaining_time') | int % 60}}m\n{%
          else %}\n  {{states('sensor.bolek_discharge_remaining_time') | int // 60}}h
          {{states('sensor.bolek_discharge_remaining_time') | int % 60}}m\n{% endif
          %}"
        x: 5
        y: 50
        size: 25
      - type: text
        value: 'In: {{states(''sensor.bolek_total_in_power'')}} W'
        x: 291
        y: 40
        anchor: rt
        size: 17
      - type: text
        value: 'Out: {{states(''sensor.bolek_total_out_power'')}} W'
        x: 291
        y: 70
        anchor: rt
        size: 17
    action: open_epaper_link.drawcustom
  mode: single
- id: '1724943986455'
  alias: Ecoflow Delta Pro turned off
  description: ''
  triggers:
  - entity_id:
    - sensor.bolek_status
    from: online
    to: offline
    trigger: state
  conditions: []
  actions:
  - target:
      entity_id:
      - open_epaper_link.0284a3393b140284
    data:
      background: white
      rotate: 0
      payload:
      - type: text
        value: Bolek
        x: 5
        y: 5
      - type: text
        value: '{{ as_timestamp(states(''sensor.date_time_iso'')) | timestamp_custom(''%d-%m-%Y,
          %H:%M'') }}'
        x: 291
        y: 10
        size: 10
        anchor: rt
      - type: line
        x_start: 5
        x_end: 291
        y_start: 25
        y_end: 25
        width: 1
        fill: red
      - type: icon
        value: power-plug-off
        x: 148
        y: 74
        size: 70
        color: black
        anchor: mm
    action: open_epaper_link.drawcustom
  mode: single
- id: '1726743163322'
  alias: Nobody at home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.family_presence
    from: 'on'
    to: 'off'
  condition: []
  action:
  - device_id: 7ad849db86e2b95823aec327de734639
    domain: vacuum
    entity_id: 1242b1258d6d6d3c96b1a87d5b98dc7b
    type: clean
  mode: single
- id: '1726743252979'
  alias: Anybody arrive home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.anton_presence
    - input_boolean.anastasiia_presence
    from: 'off'
    to: 'on'
  condition: []
  action:
  - device_id: 7ad849db86e2b95823aec327de734639
    domain: vacuum
    entity_id: 1242b1258d6d6d3c96b1a87d5b98dc7b
    type: dock
  mode: single
- id: '1732043188977'
  alias: Macropad Button 1
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.macropad_button_1
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.anastasiia_desktop_led
  mode: single
- id: '1732043474637'
  alias: Macropad Button 2
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.macropad_button_2
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - type: toggle
    device_id: f4242b9122aad3a276e0e134b9f2a77d
    entity_id: cf7bcbd7414e37970a11ade0f3633d67
    domain: light
  mode: single
- id: '1732043526352'
  alias: Macropad Button 3
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.macropad_button_3
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - type: toggle
    device_id: 66edc45b8dea066b081d650ad95decdf
    entity_id: dd725caa2799d47bb6c5eeb566a98e8b
    domain: light
  mode: single
- id: '1732104908301'
  alias: Electricity not detected
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.electricity_presence_2
    from: 'on'
    to: 'off'
  conditions: []
  actions:
  - type: turn_off
    device_id: eb6e5b4a4664fda5366635a02f6a179f
    entity_id: fa44e5ac4a0df6c54e27397459eb45ee
    domain: switch
  - type: turn_off
    device_id: cde3cbfdda2198258f8fa8a479cd3358
    entity_id: f8c3eb16e1e78bc7b12b1619d8838365
    domain: switch
  mode: single
- id: '1732104955957'
  alias: Electricity detected
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.electricity_presence_2
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - type: turn_on
    device_id: eb6e5b4a4664fda5366635a02f6a179f
    entity_id: fa44e5ac4a0df6c54e27397459eb45ee
    domain: switch
  - type: turn_on
    device_id: cde3cbfdda2198258f8fa8a479cd3358
    entity_id: f8c3eb16e1e78bc7b12b1619d8838365
    domain: switch
  mode: single
- id: '1732274654646'
  alias: Spotify display idle
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.spotifyplus_anton_isaiev
    from: playing
    to: paused
  conditions: []
  actions:
  - action: open_epaper_link.drawcustom
    target:
      entity_id: open_epaper_link.0000021ed5013b1d
    data:
      background: white
      rotate: 0
      payload:
      - type: dlimg
        url: https://storage.googleapis.com/pr-newsroom-wp/1/2023/05/Spotify_Full_Logo_RGB_Black.png
        x: 0
        y: 25
        xsize: 296
        ysize: 80
        rotate: 0
  mode: single
