- id: '1704194273528'
  alias: Create backup
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1704200208287'
  alias: Sunset light
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition: []
  action:
  - type: turn_on
    device_id: f4242b9122aad3a276e0e134b9f2a77d
    entity_id: cf7bcbd7414e37970a11ade0f3633d67
    domain: light
  mode: single
- id: '1717655923777'
  alias: Electricity not detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.tuya_plug_corridor_voltage
    from:
    to: unavailable
  condition: []
  action:
  - type: turn_off
    device_id: eb6e5b4a4664fda5366635a02f6a179f
    entity_id: fa44e5ac4a0df6c54e27397459eb45ee
    domain: switch
  - type: turn_off
    device_id: cde3cbfdda2198258f8fa8a479cd3358
    entity_id: f8c3eb16e1e78bc7b12b1619d8838365
    domain: switch
  mode: single
- id: '1717656035531'
  alias: Electricity detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.tuya_plug_corridor_voltage
    from: unavailable
    to:
  condition: []
  action:
  - type: turn_on
    device_id: eb6e5b4a4664fda5366635a02f6a179f
    entity_id: fa44e5ac4a0df6c54e27397459eb45ee
    domain: switch
  - type: turn_off
    device_id: cde3cbfdda2198258f8fa8a479cd3358
    entity_id: f8c3eb16e1e78bc7b12b1619d8838365
    domain: switch
  mode: single
- id: '1719304706918'
  alias: Anton's Desktop Led Button Single click
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: c97304da42e5614a8f03c760bfd7e3bc
    type: action
    subtype: single
  condition: []
  action:
  - type: toggle
    device_id: ec88a148fbe20ff6e69eb7c013f96172
    entity_id: 9ccec3dd1cc9a1322a4649ca7b57f53d
    domain: light
  mode: single
- id: '1720421849927'
  alias: Internet speed test
  description: ''
  trigger:
  - platform: time_pattern
    hours: /2
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
      - sensor.speedtest_download
      - automation.internet_speed_test
      - sensor.speedtest_ping
  mode: single
- id: '1723288853366'
  alias: Microgreen display
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: 0
  condition: []
  action:
  - service: open_epaper_link.drawcustom
    target:
      entity_id:
      - open_epaper_link.00000284a2053b1a
    data:
      background: white
      rotate: 0
      payload:
      - type: line
        x_start: 148
        y_start: 0
        x_end: 148
        y_end: 128
        width: 1
        fill: black
      - type: text
        value: Редиска
        font: rbm.ttf
        x: 30
        y: 5
        color: red
      - type: icon
        value: thermometer
        x: 0
        y: 40
        size: 20
        color: black
      - type: text
        value: '{{states(''sensor.microgreen_2_temperature'')}} °C'
        font: rbm.ttf
        x: 20
        y: 43
      - type: icon
        value: water-percent
        x: 0
        y: 70
        size: 20
        color: black
      - type: text
        value: '{{states(''sensor.microgreen_2_humidity'')}} %'
        font: rbm.ttf
        x: 20
        y: 73
      - type: text
        value: 'Посаджено: 07.08'
        font: rbm.ttf
        size: 15
        x: 5
        y: 113
      - type: text
        value: Цибулька
        font: rbm.ttf
        x: 175
        y: 5
        color: red
      - type: icon
        value: thermometer
        x: 150
        y: 40
        size: 20
        color: black
      - type: text
        value: '{{states(''sensor.microgreen_1_temperature'')}} °C'
        font: rbm.ttf
        x: 170
        y: 43
      - type: icon
        value: water-percent
        x: 150
        y: 70
        size: 20
        color: black
      - type: text
        value: '{{states(''sensor.microgreen_1_humidity'')}} %'
        font: rbm.ttf
        x: 170
        y: 73
      - type: text
        value: 'Посаджено: 22.07'
        font: rbm.ttf
        size: 15
        x: 155
        y: 113
  mode: single
