
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24

recorder:
  purge_keep_days: 90

mqtt:
  - light: !include_dir_merge_list mqtt/light
  - switch: !include_dir_merge_list mqtt/switch
  - sensor: !include_dir_merge_list mqtt/sensor

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
