esphome:
  name: esp-usb-socket
  friendly_name: ESP USB Socket

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SUTTUIei3Lweu1R6fqPkA64M1qcp2AfhkRauN3OG7a8="

ota:
  password: "f09754fe817074f511cf07bcebad630e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Usb-Socket"
    password: "CZDAf1AvtzhF"

captive_portal:

web_server:
  port: 80

i2c:
  sda: 0
  scl: 2

sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "Current"
    power:
      name: "Power"
    bus_voltage:
      name: "Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 5s

switch:
  - platform: gpio
    name: "Switch"
    pin: 1
    restore_mode: ALWAYS_ON