esphome:
  name: flower-humidifier
  friendly_name: Flower Humidifier

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pKWhT7fID5a+KcKPy1Ae7bxewtaHwNF9xjjki3WJKto="

ota:
  password: "ce6769e64b9824c638ba675e4bf7940d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flower-Humidifier"
    password: "dsGsO4eTLCcv"

captive_portal:

switch:
  - platform: template
    id: humidifier_switch
    name: "Switch"
    restore_mode: "DISABLED"
    turn_on_action:
      - output.turn_on: humidifier_button
      - delay: 200ms
      - output.turn_off: humidifier_button
      - switch.template.publish:
          id: humidifier_switch
          state: ON
    turn_off_action:
      - output.turn_on: humidifier_button
      - delay: 200ms
      - output.turn_off: humidifier_button
      - delay: 500ms
      - output.turn_on: humidifier_button
      - delay: 200ms
      - output.turn_off: humidifier_button
      - switch.template.publish:
          id: humidifier_switch
          state: OFF

output:
  - platform: gpio
    id: humidifier_button
    pin: D5