esphome:
  name: jysk-arnold
  friendly_name: Jysk Arnold

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NZotvZ6T9uacu4Qjs4xvpGTLKGk4eNQSbtILhRJosNM="

ota:
  - platform: esphome
    password: "bdc45f2cf3dd57e7f830c59da36eb3e0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jysk-Arnold Fallback Hotspot"
    password: "FtNgXJ6Q6LJv"

captive_portal:

web_server:
  port: 80

light:
  - platform: monochromatic
    name: "Led"
    id: arnold_led
    output: led

output:
  - platform: ledc
    id: led
    pin: 1

binary_sensor:
  - platform: gpio
    pin: 2
    name: "Switch"
    on_click:
        then:
          - light.toggle: arnold_led