esphome:
  name: jysk-christmas-light
  friendly_name: Jysk Christmas Light

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+7yZL9RmZ4eLe+JgOAVUZQKeHZR/zb7jJk66AZrQ/PM="

ota:
  - platform: esphome
    password: "5624797d7fe8fb7ba8b67adb527c9aac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jysk-Christmas-Light"
    password: "WszNGR8jp1QJ"

captive_portal:

web_server:
  port: 80

light:
  - platform: monochromatic
    name: "Led"
    id: christmas_light
    output: led

output:
  - platform: ledc
    id: led
    pin: 16

binary_sensor:
  - platform: gpio
    pin: 18
    name: "Switch"
    on_click:
        then:
          - light.toggle: christmas_light