esphome:
  name: jysk-christmas-tree
  friendly_name: Jysk Christmas tree

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nrQAimWNv4tOAEcIB/zDKJMTs2PaOscw9+zbqeex/Us="

ota:
  - platform: esphome
    password: "dc471822593ecd40721f3e185376fa3e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jysk-Christmas-Tree"
    password: "i6hkErT3iTSq"

captive_portal:

web_server:
  port: 80

light:
  - platform: monochromatic
    name: "Led"
    id: microgreen_led
    output: led

output:
  - platform: ledc
    id: led
    pin: 16