esphome:
  name: macropad
  friendly_name: Macropad

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KYMYwWLTOnMB7JQlVSHxXb5Sj5HZv5BE1AkCe0+MmSQ="

ota:
  - platform: esphome
    password: "2c519638f5c811f4ff2616ac331401e5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Macropad Fallback Hotspot"
    password: "jB8t9kovj38G"

captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    id: macropad_btn_1
    name: "Button 1"
  - platform: gpio
    pin:
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    id: macropad_btn_2
    name: "Button 2"
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    id: macropad_btn_3
    name: "Button 3"
  - platform: gpio
    pin:
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    id: macropad_btn_4
    name: "Button 4"
  - platform: gpio
    pin:
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    id: macropad_btn_5
    name: "Button 5"
  - platform: gpio
    pin:
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    id: macropad_btn_6
    name: "Button 6"