esphome:
  name: microgreen-1
  friendly_name: Microgreen 1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LDcRbzAAaAgELCsNKwW12nSb1OEeSjYP78jnFkjqRdo="

ota:
  - platform: esphome
    password: "f93d553203c7798fa0df82265f8854c7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Microgreen-1"
    password: "Wg2N5Z5W7NxW"

captive_portal:

web_server:
  port: 80

i2c:

light:
  - platform: monochromatic
    name: "Led"
    id: microgreen_led
    output: led

output:
  - platform: esp8266_pwm
    id: led
    pin: 12

switch:
  - platform: gpio
    pin: 13
    id: microgreen_fan
    name: "Fan"

binary_sensor:
  - platform: gpio
    pin: 14
    name: "Switch"
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - light.toggle: microgreen_led
      - min_length: 500ms
        max_length: 2000ms
        then:
          - switch.toggle: microgreen_fan

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s
    