esphome:
  name: microgreen-1
  friendly_name: Microgreen 1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LDcRbzAAaAgELCsNKwW12nSb1OEeSjYP78jnFkjqRdo="

ota:
  - platform: esphome
    password: "f93d553203c7798fa0df82265f8854c7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Microgreen-1"
    password: "Wg2N5Z5W7NxW"

captive_portal:

web_server:
  port: 80

i2c:

light:
  - platform: monochromatic
    name: "Led"
    output: led

output:
  - platform: esp8266_pwm
    id: led
    pin: 12

switch:
  - platform: gpio
    pin: 13
    name: "Fan"

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: " Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s
    