esphome:
  name: voltage-monitor-tecnoware
  friendly_name: Voltage Monitor Tecnoware

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "l6/gomYB+TCh9E4zrb+PiDAxRPNzZOFqo7+F33Uribs="

ota:
  password: "ad99bee408bbfa9fc16059d3c06ebfd9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Voltage-Monitor-Tecnoware"
    password: "Du0USuB9ZNVo"

captive_portal:

web_server:
  port: 80

i2c:
  - sda: 0
    scl: 2

sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    id: sensor_ina219
    bus_voltage:
      name: "Battery voltage"
      id: battery_voltage
      filters:
        - calibrate_linear:
            - 4.97 -> 5.00
            - 11.94 -> 12
    update_interval: never

  - platform: template
    name: "Battery level"
    id: battery_level
    icon: "mdi:battery"
    unit_of_measurement: "%"
    lambda: |-
      float voltage = id(battery_voltage).state;
      float min_voltage = 6.4;
      float max_voltage = 8.34;
      if (voltage <= min_voltage) {
        return 0.0;
      } else if (voltage >= max_voltage) {
        return 100.0;
      } else {
        return ((voltage - min_voltage) / (max_voltage - min_voltage)) * 100.0;
      }
    update_interval: never

interval:
  - interval: 60s
    then:
      - component.update: sensor_ina219
      - component.update: battery_level