homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  adapter: zstack
  port: /dev/ttyACM0
advanced:
  network_key:
    - 73
    - 234
    - 71
    - 48
    - 185
    - 199
    - 58
    - 1
    - 114
    - 249
    - 107
    - 144
    - 23
    - 114
    - 240
    - 212
  pan_id: 61318
  ext_pan_id:
    - 193
    - 19
    - 24
    - 65
    - 215
    - 130
    - 195
    - 225
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  transmit_power: 20
  last_seen: ISO_8601_local
device_options:
  legacy: false
devices:
  '0xa4c13833f4c3b795':
    friendly_name: Tuya T&H - Server
  '0xa4c13893629d91f8':
    friendly_name: Tuya Plug - Corridor
  '0xbc026efffe591122':
    friendly_name: IKEA VINDSTYRKA
  '0xa4c138cdcba8d262':
    friendly_name: Tuya T&H - Balcony
  '0xa4c138ca5548cd96':
    friendly_name: Tuya T&H - Living Room
  '0xa4c138f8559edb38':
    friendly_name: Tuya T&H - Corridor
  '0xa4c138ddbb0cfbb8':
    friendly_name: Tuya T&H - Kitchen
  '0xa4c13819a9c4556b':
    friendly_name: Tuya T&H - Bathroom
  '0xa4c1381790b2492b':
    friendly_name: Anastasiia's Desktop Led 1
  '0xa4c138d45bad7547':
    friendly_name: Tuya Socket - Bambu Lab A1 Mini
  '0xa4c138d371771a16':
    friendly_name: Anastasiia's Desktop Led 2
availability: true
